### ISSUE TITLE
Restructure article formats in nteractions

### ISSUE THREAD

**Issue by lyninx** [nspire/nspire#50]
the current structure for an article's json data is heavily nested, and a pain to manually update. are there better ways we can store our article + formatting? is markdown a viable option? or maybe just use plain html?

**Comment by mchandna** [comment]
- [ ] Create a frontend interface to import and format articles (don't know if we can get designs for this but if not then we can come up with something) 
- [ ] Possibly add some service type thing that can convert the data from the interface to JSON that can be posted to the API
- [ ] Hook up to the existing API to post article
